# used by local ft to make requests to wiremock
spring:
#  zipkin:
#    base-url: http://localhost:8081
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/shopping-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka