spring:
  jmx:
    enable: false
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: shopping-api
          uri: lb://shopping-api
          predicates:
            - Path=/shopping-api/**

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true