logging:
  level:
    reactor.netty: INFO
    org.springframework.cloud: TRACE
    org.springframework.web: DEBUG

server:
  port: 8080

spring:
  jmx:
    enable: false
  application:
    name: gateway
  sleuth:
    sampler:
      probability: 1.0 # 100%
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
  cloud:
    gateway:
      default-filters:
        - TokenRelay # this filter forwards the jwt access token from keycloak to downstream
        - RemoveRequestHeader=Cookie
      routes:
        - id: sales-catalog
          uri: lb://sales-catalog
          predicates:
            - Path=/sales-catalog/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:demo-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:ZhVCiZ3pyKwxWcXh5K7wC4fcnSTP3YGC} # never put a prod secret exposed in a config file - this default secret is for local env
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8081}/realms/${KEYCLOAK_REALM:shopping-api}

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus,gateway
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true