# used by local ft to make requests to wiremock
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/groot-mg

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
