server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay # this filter forwards the jwt access token from keycloak to downstream
        - RemoveRequestHeader=Cookie
      server:
        webflux:
          routes:
            - id: sales-catalog
              uri: lb://sales-catalog
              predicates:
                - Path=/sales-catalog/**
            - id: basket-service
              uri: lb://basket-service
              predicates:
                - Path=/basket-service/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:demo-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:ZhVCiZ3pyKwxWcXh5K7wC4fcnSTP3YGC} # never put a prod secret exposed in a config file - this default secret is for local env
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/${KEYCLOAK_REALM:groot-mg}

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8081}/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus,gateway,configprops
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      slo:
        http.server.requests: 5ms, 25ms, 50ms, 100ms, 150ms, 200ms, 250ms, 300ms, 400ms, 500ms, 600ms, 700ms, 800ms, 900ms, 1000ms, 1500ms, 2000ms, 2500ms, 3000ms, 4000ms, 5000ms
        http.client.requests: 5ms, 25ms, 50ms, 100ms, 150ms, 200ms, 250ms, 300ms, 400ms, 500ms, 600ms, 700ms, 800ms, 900ms, 1000ms, 1500ms, 2000ms, 2500ms, 3000ms, 4000ms, 5000ms

springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /private/api-docs
  show-actuator: false # there is a bug on security library with actuator and gateway together
  swagger-ui:
    enabled: true
    path: /private/swagger

#logging:
#  level:
#    reactor.netty: INFO
#    org.springframework.cloud: TRACE
#    org.springframework.web: DEBUG
