name: CI Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'gradle/**'
      - '**.gradle'
      - 'gradle.properties'
      - 'app/**'
      - 'ft/**'
      - '.github/workflows/ci-workflow.yml'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
          - info
          - warning
          - debug

env:
  APP_NAME: 'gateway'
  APP_PORT: '8080'
  REGISTRY: ghcr.io
  IMAGE_NAME: 'groot-mg/test/gateway'

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build + unit tests
        run: ./gradlew :app:build

      - name: Upload unit tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: |
            app/build/reports/tests/test/**/*

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app/build/libs/${{env.APP_NAME}}.jar

  functional-tests:
    needs: build-and-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app/build/libs/

      - name: Start docker containers (docker-compose)
        run: docker-compose up -d --wait

      - name: Run functional tests
        run: ./gradlew --no-daemon :ft:cucumber

      - name: Archive Cucumber test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-tests-report
          path: |
            ft/reports/cucumber-report.html

      - name: View App logs of Docker container
        if: always()
        run: docker logs app

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down

  docker-image:
    needs: functional-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app/build/libs/

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: app/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
